name: Build
on: [push, pull_request]
jobs:
  #
  # Build binaries
  #
  build_linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build
        run: OUT=mendsail-linux make build
      - name: Store binary
        uses: actions/upload-artifact@v2
        with:
          name: mendsail-linux
          path: bin/mendsail-linux
  build_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build
        run: OUT=mendsail-macos make build
      - name: Store binary
        uses: actions/upload-artifact@v2
        with:
          name: mendsail-macos
          path: bin/mendsail-macos
  #
  # Prepare a release if current commit is tagged
  #
  create_release:
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_linux, build_macos]
    steps:
      # Draft
      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
      # mendsail-linux
      - name: Download mendsail-linux
        uses: actions/download-artifact@v2
        with:
          name: mendsail-linux
          path: .
      - name: Upload mendsail-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mendsail-linux
          asset_name: mendsail-linux
          asset_content_type: application/octet-stream
      # mendsail-macos
      - name: Download mendsail-macos
        uses: actions/download-artifact@v2
        with:
          name: mendsail-macos
          path: .
      - name: Upload mendsail-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mendsail-macos
          asset_name: mendsail-macos
          asset_content_type: application/octet-stream
